### ISSUE TITLE
How can I find the square root of a ciphertext without decrypting it? How can I allow ciphertext to be transparent?

### ISSUE THREAD

**Issue by ssxssx** [s0l0ist/node-seal#143]
The second parameter of the exponential function can only be a positive integer, not 0.5.
Thank you very much!

**Comment by s0l0ist** [comment]
> The second parameter of the exponential function can only be a positive integer, not 0.5.
> 
> Thank you very much!

Unfortunately, there is no direct way to perform a square root function easily. 

However you could approximate it using methods outlined in [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4258571)

**Comment by ssxssx** [comment]
> > The second parameter of the exponential function can only be a positive integer, not 0.5.
> > Thank you very much!
> 
> Unfortunately, there is no direct way to perform a square root function easily.
> 
> However you could approximate it using methods outlined in [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4258571)

Thank you very much for your help. I have found other ways instead of calculating the square root of ciphertext, but I still need to calculate the division between ciphertext. May I ask how to calculate the division between ciphertexts ?

**Comment by ssxssx** [comment]
> > > The second parameter of the exponential function can only be a positive integer, not 0.5.
> > > Thank you very much!
> > 
> > 
> > Unfortunately, there is no direct way to perform a square root function easily.
> > However you could approximate it using methods outlined in [this paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4258571)
> 
> Thank you very much for your help. I have found other ways instead of calculating the square root of ciphertext, but I still need to calculate the division between ciphertext. May I ask how to calculate the division between ciphertexts ?

#133 You mentioned that "you could either 'divide' by multiply by the inverse," but I'm not sure how to obtain the inverse or perform division. Could you please provide me with more detailed guidance on this? Thank you very much for your help.

**Comment by s0l0ist** [comment]
For division by multiplicative inverse, you must use CKKS. Unfortunately, I am not aware of a good technique for BFV/BGV schemes. 

For example, to divide by 13 you would instead multiply by the approximate value of 1/13.

**Comment by ssxssx** [comment]
Thank you so much for your reply! But if I want to calculate the division between two ciphertexts, how can I get (1/ciphertext) according to this method?

**Comment by ssxssx** [comment]
> It is not strait-forward. See [microsoft/SEAL#143](https://github.com/microsoft/SEAL/issues/143)

Thank you so much! I would also like to ask if the secret key generation in the node-seal library is also through a random number seed? Can I assign, change, etc. to this seed directly in the library? If not, in which directory of github should I find the code related to the random number seed, I want to try to generate the same secret key twice by saving the random number seed.

**Comment by s0l0ist** [comment]
This is supported in the C++ code, but unfortunately I have not implemented it in this library. 


https://github.com/microsoft/SEAL/issues/151

May I ask your use-case?

**Comment by ssxssx** [comment]
> This is supported in the C++ code, but unfortunately I have not implemented it in this library.
> 
> [microsoft/SEAL#151](https://github.com/microsoft/SEAL/issues/151)
> 
> May I ask your use-case?

Sorry for taking so long to reply. This is just a curious idea, and I'm almost giving up on it. Thanks a lot for your answer, I'll go check out this link carefully.
