### ISSUE TITLE
Evaluator switch_key_inplace

### ISSUE THREAD

**Issue by ekampp** [s0l0ist/node-seal#146]
Hey 👋

First off. Thanks for a great package. It has really made it easy and fairly trivial to get started using FHE in my application. 

According to [this conversation](https://github.com/microsoft/SEAL/issues/76), the reference implemention has a [switch_key_inplace](https://github.com/microsoft/SEAL/blob/206648d0e4634e5c61dcf9370676630268290b59/native/src/seal/evaluator.cpp#L2523) method. 

I was wondering if you have implemented this in any capacity in this implementation? 

Best,

**Comment by s0l0ist** [comment]
Hey @ekampp, sorry for the delay.

I'm happy you've found it easy to get started :)

Unfortunately, I don't have capacity to implement the key switching implementation.
