### ISSUE TITLE
Usage question: how to check if an operation result is negative or positive?

### ISSUE THREAD

**Issue by lf94** [s0l0ist/node-seal#149]
I'm wondering about the typical example of taking someone's salary, and checking if it's below a certain amount. This should be quite easy doing `r = salary - threshold`, where if `r < 0`, it doesn't meet the threshold, but how do I express this? I can construct the necessary machinery no problem for everything but the comparison.

**Comment by s0l0ist** [comment]
Unfortunately, it is not easily achievable. You might want to ask on Microsoft's repo instead: https://github.com/microsoft/SEAL
